### ISSUE TITLE
Support callback / FIFO / RingBuffer for UPClientZenoh

### ISSUE THREAD

**Issue by evshary** [eclipse-uprotocol/up-spec#104]
Now in UPClienZenoh, we're only using the callback to implement `register_listener`.
However, it might cause the message to drop if all of them are handled in that callback.
In Zenoh, we also support handlers to put the data into the buffer (no matter FIFO / RingBuffer)

It would be better to allow developers to decide which kind of mechanism they want in getting data. (Configure in the constructor)
For example, if applications can't handle too many messages, developers can construct `UPClientZenoh` with RingBuffer to keep the last N messages and drop the older ones.

BTW, regarding getting data, we have two ways in the spec. Maybe we can have something like this:

* [register_listener](https://github.com/eclipse-uprotocol/up-spec/tree/main/up-l1#22-registerlistener): using callback
* [receive](https://github.com/eclipse-uprotocol/up-spec/tree/main/up-l1#24-receive): using RingBuffer / FIFO (based on configuration)

Let me know if I misunderstood the context. (And also tag others who need to be involved in the discussion)
@Mallets @OlivierHecart @PLeVasseur @sashacmc @stevenhartley @tamarafischer

**Comment by evshary** [comment]
Corresponding issues in the up-client-zenoh implementation:
* Rust: https://github.com/eclipse-uprotocol/up-client-zenoh-rust/issues/25
* C++: https://github.com/eclipse-uprotocol/up-client-zenoh-cpp/issues/30

**Comment by stevenhartley** [comment]
@evshary will you update the zenoh.adoc for this requirement? If not then lets close this issue and use the other issues instead

**Comment by evshary** [comment]
I'm not sure. I'll investigate it this week and reopen the issue if we need to update the spec.
