### ISSUE TITLE
Definition of response messages

### ISSUE THREAD

**Issue by sophokles73** [eclipse-uprotocol/up-spec#112]
This is the continuation of https://github.com/eclipse-uprotocol/up-core-api/issues/77
after `up-core-api` has been merged into `up-spec` as part of #91

**Comment by stevenhartley** [comment]
@sophokles73 , this PR requries an update to USubscription, Udiscovery, and UTwin protos, do we push this till after 1.5.8 or do you have a Pr for it now?

**Comment by stevenhartley** [comment]
Closing as completed
