### ISSUE TITLE
MQTT5 - authority -> topic when authority is missing and hostname is a URL

### ISSUE THREAD

**Issue by matthewd0123** [eclipse-uprotocol/up-spec#116]
Want a clarification on how to set the authority part of the MQTT Topic when there is no uAuthority and the hostname is a url instead of an ip, for example.

**Comment by stevenhartley** [comment]
I believe MQTT spec will stick with Short form URI definition which means that the UAuthority will contain IP address and/or id and not hostname. So for our usecase it will contain the VIN (when addressing a vehicle) and a different fixed id when addressing the cloud however the id's are deployment specific.

**Comment by matthewd0123** [comment]
Gonna close this out, this will be resolved by 
https://github.com/eclipse-uprotocol/up-spec/pull/121
