### ISSUE TITLE
usubcription between-device unsubscribe flow - local update?

### ISSUE THREAD

**Issue by AnotherDaniel** [eclipse-uprotocol/up-spec#119]
In [section 5.2.2](https://github.com/eclipse-uprotocol/up-spec/tree/main/up-l3/usubscription/v3#522-between-udevices) of the usubscription spec, the upper alt-part of the diagram ('up-app is the last subscriber'): after the unusbscribe call to the remote device returned, there is no update notification going to the local update channel, to indicate status change from UNSUBSCRIBE_PENDING to  UNSUBSCRIBED.

(compare 1st subscription-success case in section 5.1.2, above)

Is this by design, or an omission?

**Comment by stevenhartley** [comment]
Yes because the uApp just wants to unsubscribe and doesn't care if the remote unsubscribe is successful or not, only the uSubscription Service needs to ensure that the unsubscribe to the remote was successful or not

**Comment by stevenhartley** [comment]
@AnotherDaniel are we ok to close this?
