### ISSUE TITLE
How to invoke the Discovery API

### ISSUE THREAD

**Issue by sophokles73** [eclipse-uprotocol/up-spec#12]
Hi,

I was wondering how a uE (e.g. a client application) would interact with the Local Discovery Service? Given that there is only a proto definition, there seem to be multiple possibilities to implement the LDS, e.g. exposing a gRPC interface via HTTP2. Is the client supposed to *simply know* how to interact with the LDS or is the LDS to be invoked transparently by a uBus component instead?

**Comment by sophokles73** [comment]
Thanks for the information. However, I have to admit that I do not really understand (yet) how this whole thing is supposed to work. Is it possible to walk me (the community) through an example service invocation?

For example, let's assume that I am on a single device (in the vehicle) and I have a client application that wants to invoke one of the Kuksa Databroker's operations using uProtocol. We already have a protobuf definition of Kuksa Databroker's service endpoints and we can use standard gRPC tooling to generate a client stub for invoking the service via HTTP2. What would need to be implemented/used in order to invoke the service via uProtocol?

**Comment by sophokles73** [comment]
Any additonal thoughts, @stevenhartley ?

**Comment by sophokles73** [comment]
Awesome, looking forward to it :+1:

**Comment by stevenhartley** [comment]
Hi @sophokles73 ,
Made a number of changes in the project to push more of uTransport definitions, here is what has changed:

- uProtocol-Spec Update: https://github.com/eclipse-uprotocol/uprotocol-spec/issues/13
- Java SDK (still on a branch but you can take a look): https://github.com/eclipse-uprotocol/uprotocol-sdk-java/pull/18
- Eclipse Packages Explained: https://github.com/eclipse-uprotocol

What I still need to open source to be able to see uProtocol end-2-end in the public are:
- uprotocol-spec & uprotocol-sdk-java: RpcClient that is an interface used by uprotocol-core-api to generate client boundary objects
- uprotocol-platform-android-api: Implementation of the newly defined uTransport interface (we implemented it 3 times internally, so now we defined an interface :-))
- update to uprotocol-core-api: open source the scripts that build the boundary objects once 
- uprotocol-platform-android: A full implementation of uPlatform that can run in an emulator. Depending on how fast we can get this ready, there might be a backup plan (a different uPlatform implementation) TBD

Others developers/teams/companies are working on additional uprotocol-sdk-xxx, uprotocol-platform-xxx, etc..., as they become mature, we'll link them together hopefully with a TCK that can test IoP between SDKs and platforms.

**Comment by stevenhartley** [comment]
@sophokles73 , I'm planning to create an issue in up-core-api to add some intention revealing APIs that make it simpler to do what developers will do most, discovery services so I'm hoping to close this and open a new one in core-api, you ok with that?

**Comment by stevenhartley** [comment]
@sophokles73 close this issue for now. There will eventually be another issue for intention reviewing APIs for uDiscovery but for now there are no changes.
