### ISSUE TITLE
verify-pr CI job blocks merging of PRs

### ISSUE THREAD

**Issue by sophokles73** [eclipse-uprotocol/up-spec#143]
A PR for the up-spec repository which does not contain changes proto3 files cannot be merged.

This is because the [verify-pr job](https://github.com/eclipse-uprotocol/up-spec/blob/main/.github/workflows/build_and_test.yml) that is used for checking if the Core API protos can still be transformed into Java code, is configured as [required for each pull request in the up-spec repo](https://github.com/eclipse-uprotocol/.eclipsefdn/blob/48b5d05d879821bdc64aa6b4b597858e2083d3b1/otterdog/eclipse-uprotocol.jsonnet#L399). However, this job is [configured to only ever run](https://github.com/eclipse-uprotocol/up-spec/blob/81913286eb8ad159a02e127cae92c71de55b0a8d/.github/workflows/build_and_test.yml#L7), if some file(s) in the `up-core-api` folder are changed as well.

**Comment by sophokles73** [comment]
The way I see it, we have two options
1. configure the job to _always_ run for every PR on up-spec, or
2. do not make the job mandatory for PRs to be merged.

Personally, I would prefer option 2 in order to reduce the runtime of CI checks/build for PRs that do not change proto3 files.

@stevenhartley WDYT?

**Comment by stevenhartley** [comment]
@sophokles73 I suggest a 3rd option which is to configure the job to only run when there are changes to the up-core-api folder.

**Comment by sophokles73** [comment]
That is already the case, and that is also the problem. The job does not run when there are no changes to the up-core-api folder. But GitHub prevents merging unless the output of this job is available ....

**Comment by sophokles73** [comment]
Yes, that's option 2 ...

**Comment by stevenhartley** [comment]
OK found the bug, here is fix: https://github.com/eclipse-uprotocol/.eclipsefdn/pull/51

**Comment by stevenhartley** [comment]
Fixed by https://github.com/eclipse-uprotocol/.eclipsefdn/pull/51
