### ISSUE TITLE
Documentation issues in up-spec

### ISSUE THREAD

**Issue by int0x27** [eclipse-uprotocol/up-spec#157]
Issues in `uri.proto`:
* Consider updating according to SOME/IP decisions:
  `// 0x0000: Don't care, assume instance id of 1`:
  https://github.com/eclipse-uprotocol/up-spec/blob/630cc53e1145a5e9c9603c097a4b637379e508e4/up-core-api/uprotocol/v1/uri.proto#L42

* Clarify reserved value `0x0` for *Software Entity (uE) major version number*.
  ```
  // Software Entity (uE) major version number.
  //
  // 0x0: reserved
  // 0x1-0xFE: Major version number 1-254
  // 0xFF: Wildcard to represent all versions
  uint32 ue_version_major = 3;
  ```
  Do we need it for non SOME/IP mappings? In `vsomeip` default service major version is actually `0x0`:
  https://github.com/eclipse-uprotocol/up-spec/blob/630cc53e1145a5e9c9603c097a4b637379e508e4/up-core-api/uprotocol/v1/uri.proto#L49

* `resource_id` documentation:
  https://github.com/eclipse-uprotocol/up-spec/blob/630cc53e1145a5e9c9603c097a4b637379e508e4/up-core-api/uprotocol/v1/uri.proto#L61
    - `0x0: Default Resource id (for response messages)`: vsomeip has `Method ID` / `Event ID` for responses / notifications. Any reason 0x0 is specifically reserved?
    - note that method / event IDs ranges are suggested, not mandatory

Issues in `uattributes.adoc`.
* `uattributes.adoc` also refer to mandatory method/event ranges, consider *SHOULD*
https://github.com/eclipse-uprotocol/up-spec/blob/630cc53e1145a5e9c9603c097a4b637379e508e4/basics/uattributes.adoc?plain=1#L199 

Issues in `uri.adoc`:
* Invalid link, should be `../up-core-api/uprotocol/v1/uri.proto`
https://github.com/eclipse-uprotocol/up-spec/blob/630cc53e1145a5e9c9603c097a4b637379e508e4/basics/uri.adoc?plain=1#L70

**Comment by sophokles73** [comment]
Thanks for reporting, any chance you can create PRs for fixing the issues?

**Comment by stevenhartley** [comment]
resource_id of 0 is reserved for the default topic for receiving messages for uEs, this works well as it is the default value set when someone doesn't populate this field. Other than that please make a PR with the recommended changes.
