### ISSUE TITLE
Rename client libraries to uTransport libraries

### ISSUE THREAD

**Issue by stevenhartley** [eclipse-uprotocol/up-spec#172]
With uProtocol 1.5.8 done and being implemented in all the languages, I don't see the need for us to keep all our up-client libraries anymore as all of them will just implement uTransport. 

This PR will be used to remove the upclient.adoc spec and then rename the various up-client-xxx-yyy projects to up-transport-xxx-yyy.

**Comment by sophokles73** [comment]
> This PR will be used to remove the upclient.adoc spec and then rename the various up-client-xxx-yyy projects to up-transport-xxx-yyy. 

Reading through `upclient.adoc` I wonder who will be responsible for implementing the Layer 3 API? Is that also going into the language libraries, or do we leave that up to code generators or uEs to build this on top of the level 2 API themselves?

**Comment by stevenhartley** [comment]
L3 APIs will be auto-generated from tooling based off the L2 APIs correct.

**Comment by stevenhartley** [comment]
Completed with #176
