### ISSUE TITLE
Split UCode from UStatus

### ISSUE THREAD

**Issue by stevenhartley** [eclipse-uprotocol/up-spec#173]
Mechatronics folks would like to use UCode in their uService definitions and not be dependent on UStatus that includes strings. To avoid the uservice protos from having to include UStatus, we would like to pull UCode out from UStatus (this should not affect generated code but we will check to be sure).

**Comment by halimragab** [comment]
The main purpose of this is simplification, where embedded controllers can import UCode only and don't have to think or worry about UStatus (which includes fields that are not typically used in embedded software).
