### ISSUE TITLE
'Plug and play' Example implementations in Docker

### ISSUE THREAD

**Issue by RobertBotter** [eclipse-uprotocol/up-spec#190]
Hi everyone, this is Jon! 
As discussed in the weekly uProtocol meeting of 2024-20-06(ISO) it could be a good idea to implement an MVP per language-transport-combo with docker to make it OS-agnostic and also provide a minimal build example. 
E.g. for C++: Provide a dockerfile based on an alpine linux that runs a makefile and some script to start something like a transport library. 
By providing the dockerfile you make it easy to build and use but also you provide a code/process documentation (with the scripts) that exactly states how it needs to be done. With that, people can also alter the code/script and play around without having the need to figure out what they need to do to get it running. 

This would also enable us to puzzle ecosystems together (e.g. up-transport-rust with up-transport-java in a docker-compose-file that is based on these dockerfiles).

**Comment by stevenhartley** [comment]
We will cover this in the [service-to-signal](https://github.com/eclipse-sdv-blueprints/service-to-signal) project
