### ISSUE TITLE
W3C trace context spec only implemented half-way?

### ISSUE THREAD

**Issue by AnotherDaniel** [eclipse-uprotocol/up-spec#191]
We have the `traceparent` attribute defined in the [common message properties spec](https://github.com/eclipse-uprotocol/up-spec/blob/main/basics/uattributes.adoc#2-common-message-attributes).

[W3C Spec](https://www.w3.org/TR/trace-context/#design-overview) says:

> At a minimum they MUST propagate the traceparent and tracestate headers and guarantee traces are not broken. This behavior is also referred to as forwarding a trace.

So shouldn't we also add an optional tracestate field?

**Comment by stevenhartley** [comment]
@jefftindall, what say you?

**Comment by stevenhartley** [comment]
Since this is not currently being used, I'll close this issue till someone decides it is needed and we need to add it back.
