### ISSUE TITLE
Conceptual mismatch in uSubscription service definition

### ISSUE THREAD

**Issue by sophokles73** [eclipse-uprotocol/up-spec#31]
Hi,

while reading through the [uSubscription service spec](https://github.com/eclipse-uprotocol/uprotocol-spec/tree/v1.5.0/up-l3/usubscription/v2#3-subscription-change-notifications) I stumbled across sections 3.1. and 3.2 which seem to restrict the *topics* that the subscribers and publishers are allowed to receive change notifications for.

However, at the beginning of section 3 I found

> The uSubscription service notifies observers when there is a change in a subscription states by publishing notification events to the topic `up:/core.usubscription/2/subscriptions#Update`.

In typical pub/sub implementations (like MQTT) you would expect that a subscriber to that topic will actually receive *all* messages being published to that topic. However, the spec seems to restrict the messages that subscribers are allowed to receive based on (internal) state like the list of topics that the client has created/subscribed to. I do not see how this kind of *subscription filtering* could be implemented using existing MQTT broker implementations.

In general, to me it seems that the way that the uSubscription service's behavior is defined in the spec does not match what is generally considered pub/sub but instead calls for a dedicated notification mechanism based on subscriber/producer specific topics.

**Comment by stevenhartley** [comment]
Hi @sophokles73 , the subscription Update notification is a notification of changes to subscription states for subscribers (subscriber goes from SUBSCRIBED to UNSUBSCRIBED, etc...). This is used to handle remote subscriptions for a subscriber (to go from SUBSCRIBE_PENDING or SUBSCRIBED). 
This notification is also used when say a producer only wants to produce events (because it is costly to the system), when subscribers subscribe. The producer will register for notifications for their topic and as soon as a subscriber is subscribed, the producer is notified and the events are then produced

**Comment by stevenhartley** [comment]
AFAIK (and I'm happy to be corrected), even with other pub/sub solutions don't allow subscribers to be aware of subscriptions of other subscribers, only the broker (or producer) can be aware of the subscribers subscriptions. What we are saying is:

1. Subscriber is aware of all of their subscriptions
2. Subscription service (i.e. central broker) is aware of all subscriptions
3. Producer can be aware of all subscribers to topics it produces and NOT subscriptions to what other producers produce

**Comment by sophokles73** [comment]
> Subscriber is aware of all of their subscriptions

This is what the spec says:
> Subscribers MUST NOT call the RegisterForNotifications() as they are not permitted to receive notifications for subscription changes by other subscribers

Doesn't this mean that a Subscriber MUST NOT receive any updates to other clients' subscriptions (to other topics)? If this is the case then how could this be implemented based on a standard pub/sub message broker infrastructure (e.g. MQTT)?

**Comment by sophokles73** [comment]
> Subscription service (i.e. central broker) is aware of all subscriptions

Are you implying that the Subscription service implementation *is* the central broker? Or even, that the central (MQTT) broker would need to implement the Subscription Service? Maybe this is the overall problem here. Standard message brokers will not be able to do this because of the conceptual mismatch regarding the general concept of pub/sub and the behavior defined in the spec which I tried to point out earlier.

**Comment by sophokles73** [comment]
> Producer can be aware of all subscribers to topics it produces and NOT subscriptions to what other producers produce

This is what the spec says
> (Producers) MUST NOT be permitted to call RegisterForNotifications() for topics they do not create through the CreateTopic(), only the topics they produce

This, of course, is easy to ensure at the API level. However, at the messaging infrastructure level this would, again, mean that the messages on the subscription update topic would need to be filtered per consumer. Again, AFAIK this kind of functionality is not available in standard message broker implementations ...

**Comment by sophokles73** [comment]
> If we wanted to implement dispatcher + uSubscription using MQTT then there is are no notifications. MQTT has only SUBSCRIBE and SUBSCRIBEACK messages which would map to the uSubscription.subscribe() RPC flow.

Hmm, my understanding had been that the L3 uSubscription service is defined *on top* of the L2 uTransport. So regardless of the concrete transport implementation, there would always be a uSubscription service, or am I mistaken?

**Comment by stevenhartley** [comment]
Ideally yes but it is not always the case (a standalone service) as we are learning trying to map uProtocol to Zenoh without loosing the benefits of zenoh. 
Our existing transport implementations are not pub/sub protocols (binder, HTTP, MQTT described above) so uSubscription is a standalone service attached to homegrown event dispatchers (i.e. EventHub in Azure). When the transport is a pub/sub protocol, it gets tricky as the lines are blured for where uTransport ends and uSubscription begins. What always has to remain the same is:
a) The APIs used by uEs (how they talk to the uPlatforms through uLink libraries and the core uE APIs) 
b) Functionality of the uPlatforms (ability to subscribe to local/remote topics, etc...)
b) Platform-2-Platform communication (through streamers)

**Comment by sophokles73** [comment]
> a) The APIs used by uEs (how they talk to the uPlatforms through uLink libraries and the core uE APIs)

Ok, I guess we need to start being a little more precise when we refer to uEs. Let's use the Rust SDK as an example. My feeling is that my client code will *always* only depend on the functions of the `UTransport` trait, i.e. it will use *send*, *register_listener* etc in order to publish events and make RPC calls. However, this still allows my client to invoke operations of the *Subscription* service, doesn't it? The question now is: is there any need for my client code to do so? Is invoking the *uSubscription* service a required step? In the spec it looks like my client needs to invoke *createTopic* before it is allowed to/can publish events.

On the other hand, if I understand your earlier comment correctly, then my client code does not need to do that when using MQTT as the transport (because an MQTT broker implicitly creates an MQTT topic when a client starts publishing to it)?

**Comment by PLeVasseur** [comment]
I also had similar questions about the usage / role of uSubscription [over here](https://github.com/eclipse-uprotocol/uprotocol-spec/issues/44). Wish I would have seen this first. Perhaps we're asking the same kinds of things.

It seems to me from that other issue
> Or worded differently, is the uSubscription more a means of ensuring that the topic we'd like to receive is active and healthy, and potentially being multicated into our uDevice? It doesn't handle actually publishing / receiving and that's handled by using uP-L1 in an application. Is that correct?

**Comment by AnotherDaniel** [comment]
I have an additional questions in this context (not that we're done with the discussion so far, mind ;-) ):

Looking at usubscription.proto, specifically the EventDeliveryConfig.type and EventDeliveryConfig.attributes properties: do we maybe define the type and property names of some popular options somewhere centrally? I.e., what would we call a mosquitto-type EventDeliveryConfig?

**Comment by stevenhartley** [comment]
> > a) The APIs used by uEs (how they talk to the uPlatforms through uLink libraries and the core uE APIs)
> 
> Ok, I guess we need to start being a little more precise when we refer to uEs. Let's use the Rust SDK as an example. My feeling is that my client code will _always_ only depend on the functions of the `UTransport` trait, i.e. it will use _send_, _register_listener_ etc in order to publish events and make RPC calls. However, this still allows my client to invoke operations of the _Subscription_ service, doesn't it? The question now is: is there any need for my client code to do so? Is invoking the _uSubscription_ service a required step? In the spec it looks like my client needs to invoke _createTopic_ before it is allowed to/can publish events.
> 
> On the other hand, if I understand your earlier comment correctly, then my client code does not need to do that when using MQTT as the transport (because an MQTT broker implicitly creates an MQTT topic when a client starts publishing to it)?

- uSubscription is used to manage (across devices) subscriptions
- uTransport allows you to send & receive messages

Publishers call uSubscription.CreateTopic() to "register" their topic with the the subscription manager, then call uTransport.send() to publish their topic

Subscribers call uSubscription.subscribe() to communicate with the subscription manager that it wants to subscribe to a topic (local and/or remote), then calls uTransport.registerListener() to setup the pipe to receive the published events. uPClient implements the interface for a given uProtocol implementation and takes care of the platform (communication middleware) nuances that are different for MQTT vs zenoh vs Android Binder, etc...

**Comment by stevenhartley** [comment]
> I have an additional questions in this context (not that we're done with the discussion so far, mind ;-) ):
> 
> Looking at usubscription.proto, specifically the EventDeliveryConfig.type and EventDeliveryConfig.attributes properties: do we maybe define the type and property names of some popular options somewhere centrally? I.e., what would we call a mosquitto-type EventDeliveryConfig?

EventDeliveryConfig was a snowflake, pre-dating uTransport, requested by Cloud implementation of uProtocol to indicate where to consume the events (pull vs push in the car). We are reevaluating the need/use of this config as it could be handled within the uPClient library (and not exposed to the uE).

**Comment by AnotherDaniel** [comment]
Ok that makes sense!On Jan 22, 2024, at 16:00, Steven Hartley ***@***.***> wrote:﻿

I have an additional questions in this context (not that we're done with the discussion so far, mind ;-) ):
Looking at usubscription.proto, specifically the EventDeliveryConfig.type and EventDeliveryConfig.attributes properties: do we maybe define the type and property names of some popular options somewhere centrally? I.e., what would we call a mosquitto-type EventDeliveryConfig?

EventDeliveryConfig was a snowflake, pre-dating uTransport, requested by Cloud implementation of uProtocol to indicate where to consume the events (pull vs push in the car). We are reevaluating the need/use of this config as it could be handled within the uPClient library (and not exposed to the uE).

**Comment by stevenhartley** [comment]
Can we close this issue?

**Comment by stevenhartley** [comment]
Closing, please reopen if still needed
