### ISSUE TITLE
UUri spec uses inconsistent data types/fields

### ISSUE THREAD

**Issue by sophokles73** [eclipse-uprotocol/up-spec#34]
The [uProtocol 1.5 UUri spec](https://github.com/eclipse-uprotocol/uprotocol-spec/blob/v1.5.0/basics/uri.adoc) contains a class diagram illustrating the UUri structure and related entities.

The UAuthority interface in the diagram defines an `id` property of type `bytes`. The text in section 2.1 does not specify such a property at all.
Section 2.1 defines properies `domain`, `device`and `address` properties which are not contained in the diagram.

The UEntity interface in the diagram defines a `version` property of type `optional string`. The text in section 2.2 specifies this property as an optional integer (should rather be an unsigned integer FMPOV).
Section 2.2 specifies the type of the `id` property as `uint16` whereas the diagram defines it as `uint32`.

Section 2.3 specifies the type of UResource's `id` property as `uint16` whereas the diagram defines it as `uint32`.

**Comment by stevenhartley** [comment]
@sophokles73 can you check that the issues are now addressed?

**Comment by sophokles73** [comment]
The inconsistencies mentioned in the issue have been resolved :+1: 
However, it might be worth adding some text explaining why the IDs are defined as `uint32` in the diagram but are restricted to 16 bits in the Micro Uri format.

My understanding is that this is because there is no `uint16` type in Protocol Buffers?

**Comment by stevenhartley** [comment]
that is correct but we are investigating adding more boundaries around type definitions so we can specify bytes length, fixed sizes of 8, 16, etc...
