### ISSUE TITLE
Clarification of Micro URI requirements

### ISSUE THREAD

**Issue by PLeVasseur** [eclipse-uprotocol/up-spec#39]
Hi there 👋

Wanted a bit of help clarifying some of the language around Micro URIs:

1. Do all the fields of a Micro URI need to contain valid (nonzero) bits and be the exact length specified for each type? I'm struggling to reconcile the two following requirements:
  a. "All fields of micro UUri MUST be populated"
  b. "Wildcard is is represented in a long or short URI only when the segment is blank."

Does this mean that it is not possible to have wildcards due to requirement a? Or is requirement a combined with b saying something different?

2. It seems required to serialize to Micro form when transporting "over the wire". This means between uDevices? If so, I'm unsure how we can send Topics, RpcRequest, or RpcResponse between uDevices. The requirements I'm trying to make sense together:
    1. "MUST use the Miro Uri serialization format "on the wire""
    2. The formats of the Micro formats don't seem to include necessary pieces:
        * RPC seem to require at a minimum the UResource name and method in addition to id: "MUST return UStatus::Failed if the UUri.resource.name != "rpc" || UUri.resource.instance != "response" || UUri.resource.id != 0"
        * Topics seem to require UResource message / fragment: "MUST contain UE_NAME, UE_VERSION, RESOURCE, and MESSAGE"

Maybe I've missed how this is accomplished. Could you point me in the right direction?

**Comment by PLeVasseur** [comment]
As a follow-up, wanted to mention I saw under the [section about mapping UURIs into SOME/IP](https://github.com/eclipse-uprotocol/uprotocol-spec/tree/main/up-l1/someip#53-uris) that there was a mention of how to pack the `METHOD_ID` relevant for RPC:
![image](https://github.com/eclipse-uprotocol/uprotocol-spec/assets/11622119/ac501447-745f-4d0a-b193-59f3ed4380ec)

And I didn't see this field mentioned in the section over here [about Micro URI form](https://github.com/eclipse-uprotocol/uprotocol-spec/blob/main/basics/uri.adoc#:~:text=Table%203.%20Micro%20Uri%20Fields):
![image](https://github.com/eclipse-uprotocol/uprotocol-spec/assets/11622119/4a1f8b39-5c40-4c51-8f5a-3b2c8aa4bdf7)

**Comment by PLeVasseur** [comment]
Further, I saw there was some mention of [topics over under the section on uSubscrtiption for SOME/IP](https://github.com/eclipse-uprotocol/uprotocol-spec/tree/main/up-l1/someip#53-uris:~:text=Table%208.%20Eventgroup%20Entry%20Field%20Description):
![image](https://github.com/eclipse-uprotocol/uprotocol-spec/assets/11622119/3d6d7b52-42f5-4340-9826-8b5224b4253a)
which seemed to imply that `RESOURCE_ID` field would be repurposed for holding an id of this message assigned in the protobuf file.

Is that the case?

**Comment by stevenhartley** [comment]
Let me answer the various questions:

> 1. Do all the fields of a Micro URI need to contain valid (nonzero) bits and be the exact length specified for each type?
Yes.

> Does this mean that it is not possible to have wildcards due to requirement a?
Yes



> It seems required to serialize to Micro form when transporting "over the wire". This means between uDevices?
Wire I mean transport so not only device-2-device

>And I didn't see this field mentioned in the section over here [about Micro URI form](https://github.com/eclipse-uprotocol/uprotocol-spec/blob/main/basics/uri.adoc#:~:text=Table%203.%20Micro%20Uri%20Fields):
This is a bug, I'll fix using this PR.

**Comment by PLeVasseur** [comment]
Yup, this clears it up. Thx :heart:
