### ISSUE TITLE
Typical types of URIs, perhaps useful to make builder(s) for common types

### ISSUE THREAD

**Issue by PLeVasseur** [eclipse-uprotocol/up-spec#40]
Trying to gather some feedback on an idea.

I've been thinking about writing some kind of builder(s) to ensure a user can readily build typical URIs with all the relevant fields filled out and in resolved state without needing to reference the spec or validation code.

What are the most often used types of URIs it would be useful to have builder for?

Off the top of my head, I'm imagining:
* Topic
* RpcRequest
* RpcResponse
* NonRpc (some kind of catch all for other resolved kinds of URIs)

What do y'all think?

**Comment by AnotherDaniel** [comment]
That would be a per-SDK thing, correct? As I'm sure you are aware of, there is a rudimentary version of this in the Rust SDK (resourcebuilder in the uri module, could be extended...)

**Comment by PLeVasseur** [comment]
Hey @AnotherDaniel -- yup, seeing some of the work done in the Rust implementation (I think by you / Kai, right?) gave me some thoughts to flesh that out a bit more and help build common styles of URI.

I ended up finding a table in the `uDiscovery` spec that may be useful of [Example URIs](https://github.com/eclipse-uprotocol/uprotocol-spec/tree/main/up-l3/udiscovery/v2#:~:text=Table%203.%20Example%20URIs).

I think to your point, this may not be something that is mandated in the spec, but something that an SDK could include as an additional benefit.

What do you think? I'm considering trying to write up some sample builders for `topic` and `resource` from that table.

**Comment by stevenhartley** [comment]
@PLeVasseur what we need actually would be something that auto populates uResource numbers from names from a passed arguments of <T extends google.protobuf.Message>T   (using the protobuf descriptors), that way developers can continue to use names and we fetch the numbers from the protobuf generated code. We can talk offline on that (we get it working for one language and then extend to the others)

**Comment by AnotherDaniel** [comment]
@PLeVasseur what I've had in the original version of the rust sdk (mirroring the Java one) was builder code for all the business objects. These I threw out with the move to .proto-generated core objects (again mirroring the Java SDK) - but reading your thoughts here, and also with an eye towards making the SDK more independent of specific protobuf-handling crates, a good first step might be to reintroduce builder code for all the core objects? The builders could then also include more specialized functions for frequently needed patterns, of course.

In hindsight, I liked the builders - the Rust code generated by protoc is a bit meh to work with...

**Comment by stevenhartley** [comment]
Closing the comment, any builder support work should be covered on the language library specific issues
