### ISSUE TITLE
uSubscription::RegisterForNotifications mechanism clarification

### ISSUE THREAD

**Issue by PLeVasseur** [eclipse-uprotocol/up-spec#45]
When I read the spec and the service definition for uSubscription, I was having a hard time understanding how those uEs that are interested in learning about subscription changes receive them other than calling the uP-L1 `uTransport::registerListener()` API on the topic for subscription updates: `up:/core.usubscription/2/subscriptions#Update`

Reading the [service definition for `uSubscription::RegisterForNotifications()`](https://github.com/eclipse-uprotocol/uprotocol-core-api/blob/a05738457b685f0318f6b5b0c727e2fbf0049b4a/src/main/proto/core/usubscription/v3/usubscription.proto#L85) it appears to return a uStatus. It doesn't look like the API accommodates being given a UListener.

So I'm unclear on how the following is accomplished from the [Subscription Change Notifications](https://github.com/eclipse-uprotocol/uprotocol-spec/tree/main/up-l3/usubscription/v2#3-subscription-change-notifications) section:
> Subscribers are automatically registered to receive subscription change notifications for topics they have subscribed too through the Subscribe() API.

**Comment by stevenhartley** [comment]
Subscribers don't have to register for notifications but the topic to call regsiterListener().

**Comment by PLeVasseur** [comment]
Got it 👍
