### ISSUE TITLE
uDiscovery::FindNodes() - accepted wildcard locations / formats

### ISSUE THREAD

**Issue by PLeVasseur** [eclipse-uprotocol/up-spec#46]
I can understand from the examples given in the .proto for [`uDiscovery::FindNodes()`](https://github.com/eclipse-uprotocol/uprotocol-core-api/blob/ce0f357217a566a73762a0d95f38c01ce90d7e13/src/main/proto/core/udiscovery/v3/udiscovery.proto#L72) and in the [UURI spec on wildcards](https://github.com/eclipse-uprotocol/uprotocol-spec/blob/main/basics/uri.adoc#61-wildcard-examples) that wildcards may fall anywhere within a UURI. Can there also be multiple sections represented as wildcards?

Based on the following example from the .proto
```
uDomain: `//*.device/`
```
could we also have UURIs like the following?
1. All doors on local vehicle, whatever version, learn what methods we can call on them: `up:/*.vehicle/body.access/*/door.*`
2. Learn what topics are being published by chimes: `up:/*.vehicle/body.notification/*/chime#*`

**Comment by stevenhartley** [comment]
Support for wildcards is again implementation/deployment specific meaning that one implementation might support wildcards while others do not

**Comment by PLeVasseur** [comment]
Got it, thanks 👍
