### ISSUE TITLE
uDiscovery Database Access Permissions

### ISSUE THREAD

**Issue by PLeVasseur** [eclipse-uprotocol/up-spec#47]
Reading the [Database Access](https://github.com/eclipse-uprotocol/uprotocol-spec/tree/main/up-l3/udiscovery/v2#32-database-access) section on uDiscovery, I was wondering the mechanism by which the uDiscovery service can arbitrate and ensure which requests to modify nodes are legitimate.

It seemed like perhaps this could be done by looking in the uMessage's uAttributes at the UUID at the random portion which is generated once per uE.

Is that the mechanism by which the uLDS can confirm access permissions?

I thought that perhaps a malicious actor may be able to listen for events from the uE they want to spoof to get access to the uAttributes containing the uE's randomly generated ID. It may then be possible to craft a uMessage with the spoofed UUID to be able to modify nodes the malicious actor should not have permissions for.

Wondering if I'm missing something in the uDiscovery mechanism to validate access.

**Comment by stevenhartley** [comment]
We did not specify this in the uProtocol spec as it was assumed to be vendor/deployment specific.

**Comment by PLeVasseur** [comment]
Thanks 👍
