### ISSUE TITLE
Distributed Tracing

### ISSUE THREAD

**Issue by stevenhartley** [eclipse-uprotocol/up-spec#49]
From Jeff: 
Define optional uAttribute (traceparent) that is compatible with the [CloudEvents Distributed Tracing extension](https://github.com/cloudevents/spec/blob/main/cloudevents/extensions/distributed-tracing.md) and industry norms to support proper end-to-end observability. This is especially valuable for [more complex situations](https://github.com/cloudevents/spec/blob/main/cloudevents/extensions/distributed-tracing.md#using-the-distributed-tracing-extension). One example could be where a UE may raise an event as a result of another event.

Example:

Vehicle's session service publishes an trip started event (id=abc123)
A driver app receives the event, looks up driver's identity, and D.O.T. log to see first drive of the day. Driver app publishes shift_started event (id=xyz456, traceparent=abc123)
When an issue arises, the operational team can quickly and effectively see the correlated chain of events
For discussion: would we also want to include an optional tracestate to be more [complete](https://github.com/cloudevents/spec/blob/main/cloudevents/extensions/distributed-tracing.md#tracestate)?

**Comment by jefftindall** [comment]
I'll take it!

**Comment by jefftindall** [comment]
Order of operations:
- Merge [up-core-api PR](https://github.com/eclipse-uprotocol/up-core-api/pull/99)
- Tag release of up-core-api
- Update up-java PR with the new up-core-api tag
- Merge [up-java PR](https://github.com/eclipse-uprotocol/up-java/pull/69)
- Merge [up-spec PR](https://github.com/eclipse-uprotocol/up-spec/pull/48)
- Close this issue

It seems like reviews are pending from @stevenhartley @frankghe and/or @tamarafischer .  Your attention is appreciated.

**Comment by stevenhartley** [comment]
#48 merged, other repo code will also be merged shortly
