### ISSUE TITLE
UTransport::RegisterListener - listen to > 1 topic

### ISSUE THREAD

**Issue by PLeVasseur** [eclipse-uprotocol/up-spec#50]
Hey there 👋

Was working through the logic of implementing a `uStreamer`.

From what I understand the `uStreamer` would want to register one `UListener` with `UTransport::RegisterListener()` for each transport the `uStreamer` needs to switch over, then within the callback route to the other transports it can speak.

Reading through the spec on [`UTransport::RegisterListener`](https://github.com/eclipse-uprotocol/uprotocol-spec/tree/main/up-l1#23-registerlistener), it appears that should be possible:
> MUST support registering more than one topic per listener

But I'm unclear on how that mechanism would work: do we pass in a UURI to `UTransport::RegisterListener()` which has all wildcards? How would that work for a transport that only supports micro form?

**Comment by stevenhartley** [comment]
Hi @PLeVasseur ,
You get the UUri from one transport and then call send() to the other transport. If you receive only names and your transport only works with numbers then you have to resolve the URI before calling send() of the destination transport.
Steven.

**Comment by PLeVasseur** [comment]
Hi @stevenhartley -- perhaps I missed making my question clear.

It seemed like to me that [`UTransport::RegisterListener`](https://github.com/eclipse-uprotocol/uprotocol-spec/tree/main/up-l1#23-registerlistener) is intended to support registering a listener over `"**"`, where that would match _all_ messages "sniffed" over that transport (e.g. SOME/IP or Zenoh).

(As you say, we would then call `UTransport::send()` to send to the other transport)

Is that the case?

**Comment by stevenhartley** [comment]
> ransport (e.g. SOME/IP or Zenoh).
> 
> (As you say, we would then call `UTransport::send()` to send to

yes. We also discussed offline. Please close issue, thanks
