### ISSUE TITLE
Discovery for SDV 2.0 needs Concept Requirements to define what it should be

### ISSUE THREAD

**Issue by bzwang0186** [eclipse-uprotocol/up-spec#56]
Per meeting with workgroup prior:

uDiscovery 2.0 Concept for In-Vehicle clarifications - 1 pager needed to help answer below details.

 - what is the scope - how it will be used by uEs on CCU, uEs on CHM 
 - what data does it store - calibrations, configurations, PII? mechatronics properties? [Halim may have thoughts]
 - what is supported in non connected regions for the scope mentioned above?  *vehicle should be considered source of truth

 - how does it receive that data - at flash time? run time APIs from services themselves? discovery queries HW itself?
 
- role of CHM discovery vs CCU discovery
 - interaction between BO and vehicle ?

**Comment by stevenhartley** [comment]
Internal to GM discussion
