### ISSUE TITLE
Clarification around uP-L1 source and sink

### ISSUE THREAD

**Issue by PLeVasseur** [eclipse-uprotocol/up-spec#57]
Hi there 👋

Was in the process of implementing a uStreamer that lead to a question about the uP-L1 docs.

In the [Dispatcher spec](https://github.com/eclipse-uprotocol/up-spec/tree/main/up-l2/dispatchers) it says:
> Like IP packets, uProtocol messages (CE) have a source attribute (originator of the message) and sink attribute (where should the message be sent to). These attributes are used to route the CEs from one uE to the next if the destination is not the receiving uE.

There's a diagram at the bottom of the page with source and sink marked as I'd expect based on the above description.

If I look at the uP-L1 spec and the Rust implementation:
```rust
    async fn send(
        &self,
        topic: UUri,
        payload: UPayload,
        attributes: UAttributes,
    ) -> Result<(), UStatus>;
```
```rust
    async fn register_listener(
        &self,
        topic: UUri,
        listener: Box<dyn Fn(Result<UMessage, UStatus>) + Send + Sync + 'static>,
    ) -> Result<String, UStatus>;
```

I had assumed that the `topic` UUri of UTransport::send() gets mapped into the UMessage's source UUri by the up-client library to enable the Dispatcher to use UTransport::register_listener in order to listen for and react to all incoming CEs to route them over the other transports and then allow us to subsequently route them back to their source (for example in the case of RPC Request / Response).

However, when I read the spec for [uP-L1 UTransport::send](https://github.com/eclipse-uprotocol/up-spec/tree/main/up-l1#211-parameters), the UUri parameter is described as the destination. For me that didn't make sense together. There is already a sink UUri contained within the UAttributes, contained within the UMessage.

Can you help me square my understanding?

**Comment by stevenhartley** [comment]
True that the URI is the destination of where you want to send. So for a RPC request it is the method topic, when a response it is the uEs response topic, when a published event, it is the publish topic.

**Comment by PLeVasseur** [comment]
Does that mean the destination is then recorded twice: once in the "topic" UUri and once in the UAttributes.sink UUri?

Where does the source go? How is the source UUri obtainable when we're in a callback for a uP-L1 UTransport::register_listener()?

I'm coming at this from the POV of a uStreamer implementation where a CE is received on one transport and we need to route internally, then return the response from whence the request came.

**Comment by stevenhartley** [comment]
meaning of source and sink don't change for all event types. When you receive something on a listener, you forward to the other transport by simply calling send() (and you do not change sink and source). We talked about this live also that some transports (like the zenoh one) implements RPC using a different mechanism that isn't send() under the hood so we will take to decide if streamer to streamer is just uTransport or it could use RpcClient & RpcServer interfaces, lets continue to code and see where we land.

**Comment by PLeVasseur** [comment]
Yup, I get this now. Have more questions on uP-L2, but will open another issue if I can't figure it out. Thanks!
