### ISSUE TITLE
Dispatcher responsibilities towards UMessageType UMESSAGE_TYPE_PUBLISH and UMESSAGE_TYPE_RESPONSE  CEs

### ISSUE THREAD

**Issue by PLeVasseur** [eclipse-uprotocol/up-spec#58]
Another question as I implement a uStreamer.

There's a section in the [Dispatcher spec](https://github.com/eclipse-uprotocol/up-spec/tree/main/up-l2/dispatchers) that reads:
> Note: These communication layer requirements are still for point-2-point uE communication to and from a dispatcher

There's a section that reads:
> * MUST support At-least-once delivery policy, this means that the dispatcher will make every attempt to dispatch the CE to the intended Receiver
>   * MUST queue CEs not successfully acknowledged (transport level at-least-once delivery confirmation described above)
>   * MUST attempt to retry transmission of the CE. Retry policy is specific to the dispatcher implementation
>    * Dispatcher MUST NOT discard CEs unless either CE has expired (CE.ttl), or the egress queue is full. CEs that cannot be delivered are sent to a Dead Letter Office Topic

I think these requirements make a lot of sense for CEs with UMessageType of UMESSAGE_TYPE_REQUEST as there is some expectation of an acknowledgement.

My question is regarding UMessageType UMESSAGE_TYPE_PUBLISH and UMESSAGE_TYPE_RESPONSE  CEs.

These are, in my mind, more of a "fire and forget" style of messages.

Are the above requirements intended to hold to to them as well? If so, is there an intent to have a receiver of UMessageType UMESSAGE_TYPE_PUBLISH and UMESSAGE_TYPE_RESPONSE CEs provide some sort of acknowledgement? Is that noted somewhere in the spec?

**Comment by PLeVasseur** [comment]
I was rereading the [section on uP-L1](https://github.com/eclipse-uprotocol/up-spec/tree/main/up-l1#251-policy) and it does say:
> * Transport MUST support At-least-once delivery policy, this means that a sender MUST have a way to guarantee that the CE was successfully received by the Receiver (through the returned [UStatus])
> * Transport MUST support retransmission of CEs that are no able to be sent

Which to me does mean that even UMessageType UMESSAGE_TYPE_PUBLISH and UMESSAGE_TYPE_RESPONSE CEs are not fire and forget, and the sender must have a way to be notified under the hood at the protocol level.

This acknowledgement mechanism is outside of the scope of uProtocol and is transport layer specific?

So getting specific for a minute, would that mean that in the case of sending over up-client-zenoh, there should be some Zenoh-specific way for the caller of UTransport::send() to listen on a KeyExpr which a receiver would in turn signal on?

**Comment by stevenhartley** [comment]
@frankghe also mentioned the same thing this morning. The acknowledgement is only at L1 meaning the next hope as received it and not the final destination, will fix the wording now and use this PR.

**Comment by PLeVasseur** [comment]
Thanks for the clarification.

So to get specific for a moment, does that mean that e.g. up-client-zenoh-rust when calling uP-L1 UTransport::send() ought to, under the hood, get acknowledgement of receipt from _at least one_ uP-L1 UTransport::register_listener() on the other end?

At the moment it does a "fire-and-forget" style where [so long as the put onto the Zenoh middleware succeeded, it's considered a success](https://github.com/ZettaScaleLabs/uprotocol-rust-ulink-zenoh/blob/92e44dab603a03949700b06d14999932e7908371/src/lib.rs#L129-L148). And in order to do that put, there need not be any subscribers.

**Comment by stevenhartley** [comment]
Fixed
