### ISSUE TITLE
Definition of UMessageType identifiers

### ISSUE THREAD

**Issue by sophokles73** [eclipse-uprotocol/up-spec#63]
The [CloudEvents Common Attributes section](https://github.com/eclipse-uprotocol/up-spec/blob/main/basics/cloudevents.adoc#21-common-attributes) defines string values which must be used to encode `UMessageType`.

FMPOV these values should be defined in the [corresponding proto file](https://github.com/eclipse-uprotocol/up-core-api/blob/main/uprotocol/uattributes.proto) so that we can refer to them programmatically.

**Comment by stevenhartley** [comment]
Closing, needs to move to core-api.

**Comment by sophokles73** [comment]
See https://github.com/eclipse-uprotocol/up-core-api/issues/97
