### ISSUE TITLE
uTransport is inconsistent with uMessage definition

### ISSUE THREAD

**Issue by sophokles73** [eclipse-uprotocol/up-spec#65]
The [uTransport's send() method](https://github.com/eclipse-uprotocol/up-spec/blob/main/up-l1/README.adoc#21-send) is defined to accept three parameters. The first one being a UUri which is supposed to represent the *Destination for the UPayload*.

The [uMessage protobuf file](https://github.com/eclipse-uprotocol/up-core-api/blob/main/uprotocol/umessage.proto) defines the uMessage correspondingly:

```protobuf
message UMessage {
    // The source (address) of the message. For published events this is the producers publish topic
    // for requests it is the calling uE respose topic (who sent the request). For responses this is the
    // method URI from the uService
    UUri source = 1;

    // uProtocol mandatory and optional attributes
    UAttributes attributes = 2;

    // Optional message payload containing the data to be sent
    UPayload payload = 3;
}
```

However, the first (UUri typed) property is defined as the *source* (address) instead of the destination. The destination address of the message seems to be contained in the UAttributes' `sink` property.

**Comment by stevenhartley** [comment]
@sophokles73 thanks for pointing that out, the verbiage in up-java is right but not in the spec, I tried to fix it in #66, please review, thank you!

**Comment by stevenhartley** [comment]
Merged fix

**Comment by tamarafischer** [comment]
@sophokles73 "The first one being a UUri which is supposed to represent the Destination for the UPayload."

The first one is the **source**, meaning who is the **owner** of the payload.
The is used to provide the routing system with a very quick way of knowing the owner - someone publishing a state change or someone requesting a state change, and then the fan-out can be optimized without deserializing the UAttributes.
We know that routers/dispatchers should never touch the UPayload.
