### ISSUE TITLE
Validation of UUri when sending Publish, Request, Response type -- builders, send(), invokeMethod()

### ISSUE THREAD

**Issue by PLeVasseur** [eclipse-uprotocol/up-spec#68]
In the [`UTransport::send()`](https://github.com/eclipse-uprotocol/up-spec/tree/main/up-l1#21-send) spec we can see that there's these lines:
> * SHOULD pass resolved UUris (contains both names and numbers)
> * SHOULD use the Miro Uri serialization format

And in the [`RpcClient::invokeMethod()`](https://github.com/eclipse-uprotocol/up-spec/blob/main/up-l2/rpcclient.adoc#3-implementation) spec it's written:
> Implementations communicate to their underlining transport through the [uTransport Interface](https://github.com/eclipse-uprotocol/up-spec/blob/main/up-l1/README.adoc#_utransport).

I think in-practice we've strayed away from the above requirement that `RpcClient::invokeMethod()` be using `UTransport::send()`, particularly in the Zenoh implementation, due to the ability to use Zenoh Queryables.

I see `SHOULD` is used to specify that resolved UUris are what should be passed in and also that it `SHOULD` use Micro Uri serialization format.

A few points I think I'd like to see addressed:

1. Should `up-foolang` client libraries be opinionated about checking the UUris fit Micro Uri format or are resolved Uris when they are making builders? I'm looking at the [`Source`](https://github.com/eclipse-uprotocol/up-spec/blob/ceb40c3e218ba29241f8cc8f10aa141a7a2d3c84/languages.adoc#2-source) section on the languages spec page where there's a discussion that builders can be provided.
   * In particular, there's [some work being done](https://github.com/eclipse-uprotocol/up-rust/pull/46) over in `up-rust` to update to add a `UMessageBuilder` and reviewing the code, I was reminded of requirements from the spec. Feedback here would help.
2. Should `up-client-bartransport-foolang` `UTransport::send()` implementations be checking one or both of the above `SHOULD` lines from the spec?
3. Should `up-client-bartransport-foolang` `RpcClient::invokeMethod()` implementations be forced to use `UTransport::send()`? If not we should probably:
   * update the spec to clarify they can have a completely separate implementation of `RpcClient::invokeMethod()` which does not depend on `UTransport::send()` and also
   * add any UUri requirements we come up with for the 2. item above

Tagging @sophokles73, @stevenhartley for visibility (for some odd reason Daniel's handle doesn't come up with I "@" in this issue)

**Comment by sophokles73** [comment]
@stevenhartley Is there an expectation that every `UEntity`/`UResource` name *can* actually be resolved to a corresponding unique `u16`?

**Comment by PLeVasseur** [comment]
IIRC the name is not what's resolved to a `u16`, but the numeric portions come instead from being defined... elsewhere. I forget where.

**Comment by stevenhartley** [comment]
> @stevenhartley Is there an expectation (or provision) that every `UEntity`/`UResource` name _can_ actually be resolved to a corresponding unique `u16`?

yes. The UEntity and UResource can fully be resolved using the protobuf generated code (I have examples of that in java). We are trying to see if we can make it even more explicit and autogenerated so we don't have to call functions to build UUris but they are static variables exposed through the generated code.

**Comment by stevenhartley** [comment]
@PLeVasseur for your questions:

1. No because we could build UUris that contain only names or numbers
2. Yes
3. Torn here. If we put RPC on a separate path than pub/sub, then streamers need to go up a level to Rpcclient and RpcServer (what we talked about 2 weeks back). It is simpler if we stick with uTransport as the nuances of the RPC vs pub/sub will be transport specific as well.  Having said that this is not written in stone and we could pivot if it makes more sense for all the up implementations.

**Comment by PLeVasseur** [comment]
> 1. No because we could build UUris that contain only names or numbers

OK. So e.g. there could be different "paths" the `UMessageBuilder` could take, allowing a particular user in a `up-client-foo-rust` to choose the appropriate one for that transport, I suppose.

> 2. Yes

Which yes? :) Is this one of those "it depends on what we agree should be the on-the-wire-format for a particular transport" kind of things?

> 3. Torn here. If we put RPC on a separate path than pub/sub, then streamers need to go up a level to Rpcclient and RpcServer (what we talked about 2 weeks back).

Yeah, I get this, but in any case we should highlight in the spec that a "special" mode of `UTransport::register_listener()` is required regardless that must give access to all Request, Response, and Publish type messages coming in from a given UAuthority. I think that would resolve this issue.

> It is simpler if we stick with uTransport as the nuances of the RPC vs pub/sub will be transport specific as well.  Having said that this is not written in stone and we could pivot if it makes more sense for all the up implementations.

Not necessarily -- I think we can modify the verbiage a bit. I think facing the reality of what we're already doing with Zenoh and encoding it in the spec is a better direction. _If_ a particular transport decides to not use `UTransport::send()` under the hood for `RpcClient::invokeMethod()`, _then_ we should apply all the same requirements of URIs (and whatever else) to `RpcClient::invokeMethod()` that you originally were trying to capture by this line:
> Implementations communicate to their underlining transport through the [uTransport Interface](https://github.com/eclipse-uprotocol/up-spec/blob/main/up-l1/README.adoc#_utransport).

e.g.

> Implementations communicate to their underlining transport through the [uTransport Interface](https://github.com/eclipse-uprotocol/up-spec/blob/main/up-l1/README.adoc#_utransport). This allows the implementation to carry over the same requirements on parameters as are applied to `UTransport::send()`. If the uTransport Interface is not used to communicate using RpcClient, then RpcClient's URIs must follow requirements on [`UTransport::send()` parameters](https://github.com/eclipse-uprotocol/up-spec/blob/main/up-l1/README.adoc#211-parameters).

Probably needs some cleanup, but I hope the point shines through. WDYT?

**Comment by PLeVasseur** [comment]
bump =^)

**Comment by PLeVasseur** [comment]
From chatting with @stevenhartley offline yesterday, I realized that we walked back point 2, i.e.
* Every `RpcClient` interface _must_ be implemented on top of `UTransport`. And it sounds like `RpcServer` will be deprecated.

I think point 3. is the only open point on this issue now, which I'll boil down simply here:
> For a `UTransport::send()`, can we tune the language around this to clarify that:
> * The `UUri` MUST satisfy Micro Form
> * The `UUri` MAY be Resolved

**Comment by stevenhartley** [comment]
@PLeVasseur yes (for point 3). Can you push a PR to address this issue?

**Comment by PLeVasseur** [comment]
@stevenhartley -- opened the PR under #94

**Comment by PLeVasseur** [comment]
#94 merged, closing
