### ISSUE TITLE
RpcClient::invokeMethod() passing CallOptions

### ISSUE THREAD

**Issue by stevenhartley** [eclipse-uprotocol/up-spec#69]
Align the spec with up-java and up-rust where we pass CallOptions in lieu of UAttributes to the method as the only attribute we need is the ttl and token as the other UAttributes can be auto-generated in the implementation of invokeMethod().

**Comment by sophokles73** [comment]
@stevenhartley What about the message priority? Shouldn't that also be part of the CallOptions or is the priority fixed at CS4 for RPC requests?

**Comment by stevenhartley** [comment]
Good point, it needs to be CS4 at least but we need to be able to set it to priority other than CS4. @sophokles73 I was thinking that CallOptions should also be defined in proto, WDYT?

**Comment by sophokles73** [comment]
sure, I would suggest to add it to attributes.proto so that it is easier to keep consistent.

**Comment by stevenhartley** [comment]
This ticket is linked to https://github.com/eclipse-uprotocol/up-core-api/pull/107 that moves CallOptions to proto definition for consistency across all languages

**Comment by stevenhartley** [comment]
Merged
