### ISSUE TITLE
Should up-l2 API consist of up-l1?

### ISSUE THREAD

**Issue by evshary** [eclipse-uprotocol/up-spec#70]
The up-l1 API includes `send` and `register_listener`, while the up-l2 API includes `invoke_method` and `register_rpc_listener`.
We can find [the description](https://github.com/eclipse-uprotocol/up-spec/blob/main/up-l2/rpcclient.adoc#3-implementation) in the up-l2 rpcclient spec.

> Implementations communicate to their underlining transport through the [uTransport Interface](https://github.com/eclipse-uprotocol/up-spec/blob/main/up-l1/README.adoc#_utransport).

It means we should implement invoke_method with the up-l1 API.

However, there is no similar description in the rpcserver spec ([register_rpc_listener](https://github.com/eclipse-uprotocol/up-spec/blob/main/up-l2/rpcserver.adoc#21-registerrpclistener)).
@PLeVasseur and I discussed [this](https://github.com/eclipse-uprotocol/up-client-zenoh-rust/pull/2#discussion_r1501864774) while supporting uStreamer for upc-zenoh-rust.
I assume that all the up-l2 consists of up-l1, but just want to make sure that assumption is correct.

**Comment by evshary** [comment]
The issue is related to #73

**Comment by stevenhartley** [comment]
RpcServer is being replaced with the changes being proposed in #73

**Comment by evshary** [comment]
This can be closed now
