### ISSUE TITLE
Definition/usage of message priority is ambiguous

### ISSUE THREAD

**Issue by sophokles73** [eclipse-uprotocol/up-spec#71]
Based on the [definition of mapping common attributes to CloudEvents](https://github.com/eclipse-uprotocol/up-spec/blob/main/basics/cloudevents.adoc#21-common-attributes), my understanding is that request messages *MUST* contain a priority of at least `CS4`.

It is unclear, though, if response messages also need to contain a priority (of the same priority). This would make sense to me, because if I am interested in getting a response quickly (indicated by CS4 on the request), it seems reasonable to also require the response to be delivered high-prio, or am I mistaken?

Also, the default priority to assume when no priority is specified is defined inconsistently across the spec:
* The source mentioned above defines the default to be `CS0`
* The [QoS specification](https://github.com/eclipse-uprotocol/up-spec/blob/main/basics/qos.adoc#qos) defines the default value to be `CS1`, which also seems to be in line with the wording used in the [UAttributes proto](https://github.com/eclipse-uprotocol/up-core-api/blob/main/uprotocol/uattributes.proto) where `CS1` is described as
  
  > Standard, undifferentiated application such as General (unclassified)

FMPOV we need to adapt the *CloudEvent attributes mapping* section accordingly.

**Comment by sophokles73** [comment]
@stevenhartley WDYT?

**Comment by stevenhartley** [comment]
@sophokles73 Agree. Will you create a PR to fix this? Then we'll need to create PRs on the various language specs as well to ensure we choose CS1 as default and ensure CS4 for request and response (and they match).

**Comment by sophokles73** [comment]
@stevenhartley I was wondering if it is still appropriate to define the general requirements regarding message attributes in the [CloudEvents mapping spec](https://github.com/eclipse-uprotocol/up-spec/blob/main/basics/cloudevents.adoc). Most of the requirements stated in that document are actually independent from the way that a UMessage is being mapped to a transport.

We should probably move these requirements to the [UAttributes spec](https://github.com/eclipse-uprotocol/up-spec/blob/main/basics/uattributes.adoc) or even the corresponding proto files? WDYT?

**Comment by PLeVasseur** [comment]
> We should probably move these requirements to the [UAttributes spec](https://github.com/eclipse-uprotocol/up-spec/blob/main/basics/uattributes.adoc) or even the corresponding proto files? WDYT?

Agree. I was getting this feeling when I was reviewing the `up-core-api` change a week or so ago for priority to a `uint32` and noticed that descriptions on how priority was handled and their defaults was not in some "general purpose" location.

**Comment by stevenhartley** [comment]
> We should probably move these requirements to the [UAttributes spec](https://github.com/eclipse-uprotocol/up-spec/blob/main/basics/uattributes.adoc) or even the corresponding proto files? WDYT?

@sophokles73 agree. Lets document this in up-core-api uattribute.proto and ensure the client libraries implement this.

**Comment by sophokles73** [comment]
I have tried to do that in https://github.com/eclipse-uprotocol/up-core-api/pull/112.

However, now that I am trying to remove the corresponding information from the CloudEvents spec, I realize that the proto files are not a good place to define these general rules because there is only very limited support for documenting things, i.e. using C-type comments. Structuring the information is very difficult in proto and there is also no way of linking to certain message definitions from up-spec.

IMHO we should therefore better put the information in the textual documentation files in up-spec and use the proto files only as *technical manifestation* of the written spec.

Would that work for you @stevenhartley ?

**Comment by sophokles73** [comment]
@PLeVasseur WDYT?

**Comment by PLeVasseur** [comment]
I was also getting bummed out as I read more about Protobuf that we cannot put stronger constraints, but seems that's just how it goes.

> IMHO we should therefore better put the information in the textual documentation files in up-spec and use the proto files only as technical manifestation of the written spec.

To me, this makes sense. Would we then put above each field / message in `up-core-api` a link back to the relevant docs in `up-spec` to avoid docs drifting from the .protos?

**Comment by sophokles73** [comment]
@stevenhartley WDYT? Would you be okay with moving the info from the proto file(s) to properly formatted text documents in up-spec, e.g. uattributes.adoc?
