### ISSUE TITLE
Does RpcClient::invoke_method() require a payload or not?

### ISSUE THREAD

**Issue by sophokles73** [eclipse-uprotocol/up-spec#72]
The [RpcClient spec](https://github.com/eclipse-uprotocol/up-spec/blob/main/up-l2/rpcclient.adoc#3-implementation) defines the *UUri* IN parameter to be mandatory.
However, there is no mentioning of the payload parameter which seems to indicate that payload is optional. This would make a lot of sense to me because there will probably be methods that do not require any input.

In any case, IMHO we should make it more explicit if parameters are mandatory or optional.

**Comment by stevenhartley** [comment]
merged
