### ISSUE TITLE
The Implementation requirements of InvokeMethod are not aligned to the API definition 

### ISSUE THREAD

**Issue by MelamudMichael** [eclipse-uprotocol/up-spec#82]
API definition - OUT Future [UMessage](https://github.com/eclipse-uprotocol/up-spec/blob/main/basics/umessage.adoc) invokeMethod(IN [UUri](https://github.com/eclipse-uprotocol/up-spec/blob/main/basics/uri.adoc), IN UPayload?, IN [CallOptions](https://github.com/eclipse-uprotocol/up-spec/blob/main/basics/uattributes.adoc))

MUST return INVALID_PARAMETER if UUri is null or empty or CallOptions.priority() < CS4

MUST return ALREADY_EXISTS if the same request already exists (i.e. same UUri and CallOptions). This is to prevent duplicate requests.

MUST complete future successfully when the response is received from the server.

While the Method returns a future , it is not possible to return a status

**Comment by PLeVasseur** [comment]
Looks like in [`up-java`](https://github.com/eclipse-uprotocol/up-java/blob/6f17b8e28646393917c65935818eaa9d23e80c4c/src/test/java/org/eclipse/uprotocol/rpc/RpcTest.java#L218-L237) and [`up-rust`](https://github.com/eclipse-uprotocol/up-rust/blob/b4ae3e1f22c181836531aaeea3068c907f172e78/src/rpc/rpcmapper.rs#L364-L373) there's a concept of an RpcMapper in order to make it possible to handle the returned UStatus.

Is this to what you refer?

**Comment by tamarafischer** [comment]
My two cents on InvokeMethod. 
IMHO invoke method should not return a UMessage. 
UMessage should be used for publish and notification messages.
For RPC the developer interface should be more like the Rust Result object.

URpcResult
UStatus rpcStatus -> provides an answer for success, failure and failure reason
UPayload the RPC response payload

This new message is wrapped in the invoke  a CompletionStatge (a Future)

CompletionStage<URpcResult> invokeMethod

IMHO this is the interface provides a strongly typed RPC that has 2 clear parts - the payload (maybe even an Optional<Payload> in the case of failure, and the actual uPayload with the response.

@MelamudMichael this is what we talked about, what do you think?

**Comment by MelamudMichael** [comment]
I agree with you !

**Comment by stevenhartley** [comment]
Michael and Tamara, can you please put forth a proposal in up-cpp and up-java?

**Comment by MelamudMichael** [comment]
@stevenhartley - Please see here 
https://github.com/MelamudMichael/up-cpp/blob/feature/rpc_alignment/include/up-cpp/rpc/RpcClient.h

As an example few scenarios where it is needed -

1. invokeMethod returned valid future , timeout received so the payload will be nullptr, but nullptr is also a valid response , so there is no way for the user to know that a timeout occurred
2. invokeMethod returned valid future , but no RPC server is available

**Comment by stevenhartley** [comment]
Recommended API from Michael:

````
UStatus invokeMethod(const uprotocol::v1::UUri &topic,
const uprotocol::utransport::UPayload &payload,
const uprotocol::v1::CallOptions &options
const uprotocol::utransport::UListener &callback) = 0;
````

**Comment by tamarafischer** [comment]
> Recommended API from Michael:
> 
> ```
> UStatus invokeMethod(const uprotocol::v1::UUri &topic,
> const uprotocol::utransport::UPayload &payload,
> const uprotocol::v1::CallOptions &options
> const uprotocol::utransport::UListener &callback) = 0;
> ```

How can invokeMethod return a UStatus? Should it not return the specified payload in the rpc proto definition?

IMHO this is not a very good API, it deviates way too much from the specification in the protobuf.

Why can't we simply return an rpcResponse object?
Is there a problem with adding a new object?

Like @PLeVasseur mentioned, we already have the Monad defined in the Java implementation. 
We can keep it simpler if it makes more sense but returning a UStatus seems incorrect.

**Comment by tamarafischer** [comment]
Here is code that takes a HTTP request to invoke the say hello method
```

    Mono<ServerResponse> invokeMethodSayHello(ServerRequest request) {
       
        // the rpc request processing pipeline
        return request.bodyToMono(SayHelloRequest.class)
                .doOnNext(sayHelloRequest -> logger.info("[PlaygroundAppHttpHandler][invokeMethodSayHello] SayHelloRequest {}",  sayHelloRequest))
                .flatMap(sayHelloRequest -> {

                    final UMessage uMessage = buildSayHelloRPCMessage(sayHelloRequest);
                    final String requestId = LongUuidSerializer.instance().serialize(uMessage.getAttributes().getId());

                    Function<UProtocolDatabaseRpcClientSupport.RPCResponse, SayHelloResponse> mapper = (rpcResponse) -> {
                        final String responsePayload = rpcResponse.protoPayload().isBlank() ? "" :
                                HelloResponsePayloadExtractor.instance().parseBase64ProtobufStringWrapped(rpcResponse.protoPayload())
                                        .map(HelloResponse::getMessage).orElse("Unable to unpack hello response");
                        return new SayHelloResponse(requestId, rpcResponse.vin(),
                                rpcResponse.responseStatus().name(),
                                responsePayload, lastUpdatedFormatted(rpcResponse.lastUpdated()));
                    };

                    return uProtocolRpcClient.invokeMethod(sayHelloRequest.vin(),
                            uMessage.getSource(), uMessage.getPayload(), uMessage.getAttributes(), mapper);
                })
                .flatMap(sayHelloResponse -> ok().contentType(MediaType.APPLICATION_JSON)
                        .bodyValue(sayHelloResponse));
    }
```


 ```
   public <T> Mono<T> invokeMethod(String vin, UUri uUri, UPayload uPayload, UAttributes uAttributes,
                                    Function<UProtocolDatabaseRpcClientSupport.RPCResponse, T> responseMapperFunction) {

        return addTokenCredentials(uAttributes, uUri)
                .flatMap(uAttributesWithToken -> Mono.just(uTransport.send(uUri, uPayload, uAttributesWithToken)))
                .flatMap(uStatus -> UCode.OK.equals(uStatus.getCode()) ? Mono.just(uStatus) :
                        Mono.error(new RuntimeException(String.format("Invoke Method failed, UTransport Failed to send command %s. %s",
                                LongUriSerializer.instance().serialize(uAttributes.getSink()),
                                uStatus.getMessage().isBlank() ? "" : String.format("Reason: %s", uStatus.getMessage())))))
                .flatMap(uStatus -> {
                    final UProtocolDatabaseRpcClientSupport.RpcRequest rpcRequest = new UProtocolDatabaseRpcClientSupport.RpcRequest(uAttributes.getId(), vin, uAttributes.getSink());
                    final String requestId = LongUuidSerializer.instance().serialize(uAttributes.getId());
                    return uProtocolDatabaseRpcClientSupport.registerRpcRequest(rpcRequest)
                            // poll for response every 3 seconds
                            .flatMap(l -> Flux.interval(tickDuration)
                                    // timeout after 5 minutes (300 seconds)
                                    .flatMap(tick -> tick < timeoutAfterNumberOfTicks ? uProtocolDatabaseRpcClientSupport.findRpcResponseByRequestId(requestId) :
                                            Mono.just(new UProtocolDatabaseRpcClientSupport.RPCResponse(uUri, uAttributes.getId(), vin,
                                                    RpcResponseStatus.TIMEOUT, "", Instant.now())))
                                    // stop once the status is no longer requested
                                    .filter(rpcResponse -> !RpcResponseStatus.REQUESTED.equals(rpcResponse.responseStatus()))
                                    .next()
                                    // use the mapper function to return the correct response type
                                    .map(responseMapperFunction)
                            );
                });
    }
```


The code manages RPC requests and responses through a database using non-blocking IO constructs of project reactor (Mono/Flux) - instead of Futures (which can also be added if needed)

Even with this implementation, I still think that having a dedicated RpcResponse object in the core is a good idea.

**Comment by MelamudMichael** [comment]
> > Recommended API from Michael:
> > ```
> > UStatus invokeMethod(const uprotocol::v1::UUri &topic,
> > const uprotocol::utransport::UPayload &payload,
> > const uprotocol::v1::CallOptions &options
> > const uprotocol::utransport::UListener &callback) = 0;
> > ```
> 
> How can invokeMethod return a UStatus? Should it not return the specified payload in the rpc proto definition?
> 
> IMHO this is not a very good API, it deviates way too much from the specification in the protobuf.
> 
> Why can't we simply return an rpcResponse object? Is there a problem with adding a new object?
> 
> Like @PLeVasseur mentioned, we already have the Monad defined in the Java implementation. We can keep it simpler if it makes more sense but returning a UStatus seems incorrect.

You return a UStatus because the UPayload will be returned through the user provided callback 

the original InvokeMethod is asynchronous and returns you a future
this flavor of InvokeMethod  is also asynchronous but instead it will trigger the callback once a response is received
if you want to return UPayload from InvokemMethod then if will be a blocking API , and this is not what we want

**Comment by stevenhartley** [comment]
@MelamudMichael Please file an issue on up-cpp and not up-spec as I believe the API change would be only for up-cpp
