### ISSUE TITLE
Should we Bring Back Short Form URI?

### ISSUE THREAD

**Issue by stevenhartley** [eclipse-uprotocol/up-spec#83]
Older version of [uri.adoc](https://github.com/eclipse-uprotocol/up-spec/blob/e4ad95ff1a7e8d1dfb806f095131eb8172a123a2/basics/uri.adoc) use to also have a URI format called Short Form. Short URI was a string representation of the numbers inside of UUri object, example below:

`up://192.168.1.100/2/1.1/5000`

In the above example. UAuthority was the IP address, uService id is 2, verison of the service is 1.1, and the topic ID (the publish topic) was 5000. 
It was thought that this version would not be needed so it was removed from up-java and the specification **however** we see strong benefits of this URI format for zenoh and MQTT that require strings for topic names. 

This issue is to address if we should bring back short form URIs for zenoh & MQTT (and possibly other transports) in lieu of micro form that is difficult to use unless you're writing raw bytes to a transport "wire".

**Comment by evshary** [comment]
From Zenoh perspective, using the short URI is easier to generate Zenoh key.

* Long URI: Need to deal with escaping illegal character in Zenoh
* Micro URI: Need to transform the binary into hex string

However, I'm just wondering whether this will cause a problem for users if they need to define Long/Short/Micro format while declaring the UURI?

**Comment by PLeVasseur** [comment]
I think this makes a lot of sense for protocols like MQTT and Zenoh.

@evshary -- btw, just wanted to make sure that you're still able to take a UUri containing only a UAuthority and still form a Zenoh KeyExpr then like this: `up://192.168.1.100/**`

You may need to submit a PR upstream to `up-rust` to add functionality to serialize only a UAuthority to long form / string.

**Comment by evshary** [comment]
Hi @PLeVasseur 

> btw, just wanted to make sure that you're still able to take a UUri containing only a UAuthority and still form a Zenoh KeyExpr then like this: up://192.168.1.100/**

I think I still need to do some minor transformations.

* with UAuthority: `upr/192.168.1.100/4/1`	
* w/o UAuthority: `upl/4/1`
* For the special UUri: `upr/192.168.1.100/**`

> You may need to submit a PR upstream to up-rust to add functionality to serialize only a UAuthority to long form / string.

Do you mean short form?

**Comment by PLeVasseur** [comment]
> I think I still need to do some minor transformations.

Makes sense to me.

> Do you mean short form?

Perhaps? I'm unclear on if long and short form differ when it comes to the UAuthority, since it seems like in [any case they are turned into string representations](https://github.com/eclipse-uprotocol/up-spec/blob/main/basics/uri.adoc#41-long-uris).

**Comment by evshary** [comment]
> Perhaps? I'm unclear on if long and short form differ when it comes to the UAuthority, since it seems like in [any case they are turned into string representations](https://github.com/eclipse-uprotocol/up-spec/blob/main/basics/uri.adoc#41-long-uris).

Yes, but only the IP format is available in short form. While considering long form, we might need to deal with some special characters.

**Comment by PLeVasseur** [comment]
Oh really? I think it's also possible to use the id. Basically either of the two numeric representations of UAuthority, ip or id. I think @stevenhartley answered that way to @tamarafischer when it came up in our meeting.

**Comment by evshary** [comment]
I saw it from the old spec. Maybe we can check with @stevenhartley 
![image](https://github.com/eclipse-uprotocol/up-spec/assets/456210/8889518e-1871-4f1f-bcda-9b593652e248)
If there is no special character in UAuthority, then that's fine with Zenoh key.

**Comment by stevenhartley** [comment]
resolved in the spec
