### ISSUE TITLE
How to include Zenoh configuration into UPClientZenoh?

### ISSUE THREAD

**Issue by evshary** [eclipse-uprotocol/up-spec#85]
The issue is mainly for discussing how to configure Zenoh while using `UPClientZenoh`.
As we discussed in the meeting, we can construct the `UPClientZenoh` by [passing the Zenoh Config as an argument](https://github.com/eclipse-uprotocol/up-client-zenoh-rust/blob/8855b9abd4bd27228d30d9061522194f330fa547/src/lib.rs#L52).

While there are so [many configurations](https://github.com/eclipse-zenoh/zenoh/blob/65e0fb7519617813781faeb281d85eee977117cc/DEFAULT_CONFIG.json5) in Zenoh, it's difficult for users to understand how to configure it.

Maybe a better way is to pick some common-used configurations, and use them while constructing `UPClientZenoh`.
At least the node mode (peer, client, router) is what we need.

Still, I prefer to reserve the flexibility for advanced users to use Zenoh configuration directly.

**Comment by PLeVasseur** [comment]
Yeah, we should flesh out in the spec the most common sets of configurations. Hmmm.

Maybe we can ask @stevenhartley to identify parts of the architecture diagram at a minimum that would need to be:
* client
* peer
* router

And then we can get into more details around what each may need.

WDYT?

**Comment by stevenhartley** [comment]
@PLeVasseur & @evshary the topology diagram does show what is a peer vs plugin vs client.

**Comment by PLeVasseur** [comment]
@evshary -- okay, @stevenhartley is right, I missed he already had them labeled.

I agree we should keep an option to pass in a config for advanced use cases.

So I suppose we could start with three new functions to create a UPZenohClient: `new_client()`, `new_router()`, and `new_peer()` which use an appropriate Zenoh config under the hood.

Are there some particular configuration parameters that you think would be worthwhile to expose for any of those three?

**Comment by evshary** [comment]
@stevenhartley @PLeVasseur 
I created a PR here for you to check whether this is what we expect.
https://github.com/eclipse-uprotocol/up-client-zenoh-rust/pull/20

Besides Zenoh mode (peer, client, router), I also added the listen and connect endpoints in the configuration.
You can check here
https://github.com/eclipse-uprotocol/up-client-zenoh-rust/pull/20/files#diff-b1a35a68f14e696205874893c07fd24fdb88882b47c23cc0e0c80a30c7d53759R42

If we all agree with the changes, then I'll update the up-spec.

**Comment by MelamudMichael** [comment]
@evshary  it looks similar to what i done here - 
https://github.com/eclipse-uprotocol/up-client-zenoh-cpp/pull/21/files#diff-3b10e8ebe4efaab2cad64a30ed5f7e75a0409fd8283ca336e86b169e28daa9b2R61

**Comment by evshary** [comment]
For the Zenoh configuration, I think I shouldn't create another struct for the subset of Zenoh configuration based on the meeting conclusion.
Then I'll have two constructors for the time being:

`UPClientZenoh::new()`: Using default configuration
`UPClientZenoh::new_with_zenoh_config(config: Config)`: Using Zenoh config, which is mainly for advanced users

I'm considering having more constructors based on the different roles in the topology in the roadmap, but I guess I might need more context about how other components work.
Let's keep watching.

@MelamudMichael For the configuration for only UPClientZenoh (Not Zenoh), I'll create another issue to discuss it.

**Comment by PLeVasseur** [comment]
@evshary, @MelamudMichael -- what do you think about the proposal I made over on CY's [PR](https://github.com/eclipse-uprotocol/up-client-zenoh-rust/pull/20#issuecomment-2009758018)?

I suppose this may be a better place to centralize that discussion since it's relevant to both the C++ and Rust implementations.

**Comment by evshary** [comment]
Hi @PLeVasseur 
Your proposal to have an abstraction behind the UPClientZenoh is a good design.
However, before we take that decision, I recommend we list all the roles needed by the topology and describe their requirements explicitly.
It can avoid premature optimization.

For example:
As far as I know, we might only need peer and router mode in the topology, so we can ignore client mode settings.
Also, when it comes to connection, I also want to know whether the entity in Linux (up-zenoh) can connect to each other with multicast or not. If yes, then we don't need to have `listen address` and `connect address` settings inside Linux (up-zenoh). (But might still need them when it comes to inter-router connection)
![image](https://github.com/eclipse-uprotocol/up-spec/assets/456210/811b5044-7a4d-4d96-aa45-7b8279257484)

Maybe we'll find out that more configuration settings are needed / not needed as more components are done.
Then we can have a better optimization.

BTW, I didn't notice the difference between UPClientZenoh and UPZenohClient before your reminders below 😆

**Comment by PLeVasseur** [comment]
> BTW, I didn't notice the difference between UPClientZenoh and UPZenohClient before your reminders below 😆

:upside_down_face: 

> As far as I know, we might only need peer and router mode in the topology, so we can ignore client mode settings.

I had snipped only a portion of the topology diagram, you can take a look at the roadmap document for more bits, but here's an example of several nodes that are Clients:
![image](https://github.com/eclipse-uprotocol/up-spec/assets/11622119/b392d815-29db-4e27-b266-cd31c85829ed)

> However, before we take that decision, I recommend we list all the roles needed by the topology and describe their requirements explicitly.

Strongly agree!

> Maybe we'll find out that more configuration settings are needed / not needed as more components are done.

This is where I thought having a series of light wrappers around `UPClientZenoh` would be the most flexible to change as we go without having to actually modify `UPClientZenoh` as we pivot.

**Comment by evshary** [comment]
@MelamudMichael 
Let me list what we need while initializing UPClientZenoh here

* Zenoh Configuration
* UAuthority and UEntity

Please let me know if there are other configurations you need, and I can put them into spec.

**Comment by stevenhartley** [comment]
@evshary , Do we have enough to close this issue with updates to zenoh.adoc?

**Comment by evshary** [comment]
Zenoh Configuration and UAuthority+UEntity are all defined in #103. Now the remaining is how we can make the configuration easier, but I think it should depend on how users use it. Maybe we can close it and create another update after we collect enough use cases from users.

**Comment by stevenhartley** [comment]
> WDYT?

I like it to make it simpler for developers but before we do this lets make sure the first (with config) works. For the client mode, we need to set the IP address and port of the router we want to connect to no?

**Comment by evshary** [comment]
Yes, we need the address and port in client mode.
I updated the example code to show how to use struct / file to configure Zenoh.
https://github.com/eclipse-uprotocol/up-zenoh-example-rust/pull/5/files#diff-a990dc6fb21d6b911a96ebc9bf1db1bf13d9692eab3c114cc7819a6172953622R67

**Comment by stevenhartley** [comment]
@evshary please help to close/address this open topic.
