### ISSUE TITLE
Merge up-spec and up-core-api

### ISSUE THREAD

**Issue by stevenhartley** [eclipse-uprotocol/up-spec#88]
up-spec contains the documentation and requirements for the protocol while up-core-api holds the protos that are also part of the specifocations however they were split into separate projects early on (do not recall the justifications). 

Having the spec and code in different locations are making tagging releases more difficult not to mention they reference each other often.

**Comment by sophokles73** [comment]
@stevenhartley this is the right thing to do :+1: 
I would like to create a PR for https://github.com/eclipse-uprotocol/up-spec/issues/71 which adds the relevant UAttributes requirements/constraints to uattributes.adoc.
FMPOV it would make sense to create the PR towards the [core-api-merge](https://github.com/eclipse-uprotocol/up-spec/tree/core-api-merge) branch. Would you agree?

**Comment by stevenhartley** [comment]
Done
