### ISSUE TITLE
Configuration Sync among different UPClientZenoh implementations

### ISSUE THREAD

**Issue by evshary** [eclipse-uprotocol/up-spec#95]
@MelamudMichael Would you please share the configuration for only UPClientZenoh?
I think we need to sync between Rust and C++.

Now in Rust, I believe we only plan to initiate UPClientZenoh with `UAuthority` and `UEntity`, which is in @PLeVasseur's [PR](https://github.com/eclipse-uprotocol/up-client-zenoh-rust/pull/19)

After listing them, we should add them to [the Zenoh spec](https://github.com/eclipse-uprotocol/up-spec/blob/main/up-l1/zenoh.adoc).

**Comment by PLeVasseur** [comment]
Oh yes! This is actually a great place to ensure we're on the same page about that bit.

@stevenhartley has said in the past we need to be able to build a UUri internally for `invoke_method()`, so I added a `UAuthority` and `UEntity` to the constructor and what's held by the `UPClientZenoh` implementation.

I hope that made sense @evshary, @MelamudMichael :slightly_smiling_face:

**Comment by PLeVasseur** [comment]
@evshary -- do you wanna close this one in favor of #85?

**Comment by evshary** [comment]
Now we have two kinds of configurations to discuss:
1. How to pass Zenoh configuration in the constructors
2. What kinds of extra configuration UPClientZenoh needs for initialization
Maybe we can discuss these two in #85 if you think it can keep the issue list cleaner.
