### ISSUE TITLE
What is the minimum viable UUri to pass `UTransport::registerListener() / unregisterListener()`?

### ISSUE THREAD

**Issue by PLeVasseur** [eclipse-uprotocol/up-spec#98]
In #94 we clarified that for `UTransport::send()` the minimum viable UUri contained within the UMessage passed in must be in Micro Form

I'm wondering about `UTransport::registerListener() / unregisterListener()`

Perhaps the same language can be used for `UTransport::registerListener() / unregisterListener()`:
* **MUST** pass UUris for which `isMicroForm()` return true
* **SHOULD** pass Resolved UUris (contains both names and numbers)

WDYT?

Tagging in @stevenhartley & @sophokles73

**Comment by sophokles73** [comment]
sounds good to me

**Comment by stevenhartley** [comment]
Agree as well, @PLeVasseur please push the spec update. Thank you

**Comment by PLeVasseur** [comment]
> Agree as well, @PLeVasseur please push the spec update. Thank you

Sounds good. Opened #101 for this :slightly_smiling_face:

**Comment by PLeVasseur** [comment]
Done in #101, closing!
